### ISSUE TITLE
Error importing from cryosparc curate job

### ISSUE THREAD

**Issue by KatrinaABlack** [r-karimi/vesicle-picker#3]
Hi! I've been trying to import from a cryosparc curate job (P17) but am receiving an error that the micrograph cannot be found:

2024-08-14 11:12:37,930 get_project_file     ERROR    | Invalid file path J1/imported/017646539750839992624_filename_mic_DW.mrc; must be in project directory for P17

This can be fixed by copying micrographs into P17 from P1, but it appears the symlinks in P17 aren't working. Is there a way of addressing this?

**Comment by r-karimi** [comment]
Hi Katrina, is this an issue with the download_micrographs function in vesicle picker? Given your project configuration, are you able to load a micrograph into python using only functions from cryosparc-tools?

**Comment by KatrinaABlack** [comment]
No, I can't. The exact error I receive if I try to load a micrograph using cryosparc tools in a notebook depends on the version of cryosparc tools. We have cryosparc v4.4.1 and if I use tools 4.4.1, I get an [Errno 2] No such file or directory, and if I use tools 4.5.1, I get a: 
HTTP Error 500 INTERNAL SERVER ERROR; please check cryosparcm log command_vis for additional information.
Response from server: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\. The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'

It might be helpful to know which versions of cryosparc-tools and cryosparc are working for you?

**Comment by r-karimi** [comment]
Hm, sounds like it might be an issue with cryosparc-tools. Our version of cryosparc and cryosparc tools has been updated periodically during the development of the code. It was first developed on cryosparc v4.4 and later on v4.5. I have yet to run into an issue with importing micrographs from our server.

I wonder if the directory structure in your P17 is causing problems. Maybe cryosparc-tools doesn't recognize your symlinks? What happens if you run an import micrographs job in P17 pointing to the micrographs from P1, and then a curate job using the outputs of that import micrographs job?

**Comment by KatrinaABlack** [comment]
Replacing all the symlinks with a regular file that is renamed with the correct UID does make the program work, so it does seem to be a symlink problem. "P17" is the project file for this collection, "P1" is a completely different dataset/project entirely so it wouldn't make sense to point to any files from P1. This seems to be an issue with cryosparc tools and symlinks, as all the jobs (import/curate) are still in the same project directory. I think the best workaround is using non-symlinked files for now, but hopefully this will be addressed in cryosparc tools.

**Comment by r-karimi** [comment]
Good to know, thanks for finding a workaround. It might be worth posting a minimal example reproducing the error on the [cryosparc-tools](https://github.com/cryoem-uoft/cryosparc-tools) Github page. I'll mark this issue as closed for now, but please feel free to re-open it if any downstream errors are caused because of your workaround.
